language: generic
sudo: false

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTEST_OPTIONS='-v --ignore=it/'
        - MPLBACKEND=Agg

matrix:

    include:

        # Check for sphinx doc build warnings
        # - os: linux
        #   env: CMD='sphinx-build'

        # macOS
        - os: osx
          env: PYTHON_VERSION=3.6
        - os: osx
          env: PYTHON_VERSION=2.7

        # Linux
        - os: linux
          env: PYTHON_VERSION=3.6
        - os: linux
          env: PYTHON_VERSION=3.5
        - os: linux
          env: PYTHON_VERSION=2.7

        # Run regression tests
        # - os: linux
        #   env: PYTEST_OPTIONS='-v --ignore=tests'

install:
    - source ci/travis_setup_conda.sh

script:
   - flake8 lens
   - py.test $PYTEST_OPTIONS
